# action.yml
name: 'Build Packer Image'
description: 'Builds a Packer Image (and optionally Vagrant box)'
inputs:
  template:
    description: 'Template to build'
    required: true
    default: 'template.pkr.hcl'
#outputs:
#  time:
#    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.template }}